version: '3'
services:
  code:
    build:
      context: ./code
      dockerfile: Dockerfile
    volumes:
      - $PWD/code:/code
    env_file:
      - $PWD/.env
    ports:
      - "8888:8888"
  postgres:
    build:
      context: postgres
    restart: always
    env_file:
      - $PWD/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    env_file:
      - $PWD/.env
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

volumes:
  postgres:
  mongodb:
